import "../css/output.css";
import Annoying from "./header/annoying";
import Search from "./header/console";
import Location from "./header/location";
import NavBar from "./header/navbar";
import Setting from "./header/setting";
Annoying();
Setting();
Search();
NavBar();
Location();
