import "../css/output.css";
import Story from "./Body/Story";
import Annoying from "./header/annoying";
import Search from "./header/console";
import Location from "./header/location";
import NavBar from "./header/navbar";
import Setting from "./header/setting";
import Slider from "./Body/Slider";
import Mlocation from "./Mheader/Mlocation";
import MSearch from "./Mheader/MSearch";
import Services from "./Mheader/MServices";
import List from "./Body/List";
import Incredible from "./Body/Inc";
import Ads from "./Body/Ads";
import Amazing from "./Body/amazing";
import Grouping from "./Body/Grouping";
import Partner from "./Body/Partner";
import Brands from "./Body/Brands";
import Options from "./Body/Options";
import OptionsM from "./Body/OptionsM";
import Indemand from "./Body/Indemand";
import chosen from "./Body/chosen";
import Hot from "./Body/Hot";
import Blog from "./Body/Blog";
import Footer from "./Body/Footer";
import "./fixedButton";
import Menu from "./Body/Menu";
import Tabs from "./Body/Tabs";

Annoying();
Setting();
Search();
NavBar();
Location();
Services();
MSearch();
Mlocation();
Story();
Slider();
List();
Incredible();
Ads();
Amazing();
Grouping();
Partner();
Brands();
Options();
OptionsM();
Indemand();
chosen();
Hot();
Blog();
Footer();
Menu();
Tabs();