import "../css/output.css";
import Slider from "./Body/Slider";
import Story from "./Body/Story";
import Annoying from "./header/annoying";
import Search from "./header/console";
import Location from "./header/location";
import NavBar from "./header/navbar";
import Setting from "./header/setting";
import Mlocation from "./Mheader/Mlocation";
import MSearch from "./Mheader/MSearch";
import Services from "./Mheader/MServices";
Annoying();
Setting();
Search();
NavBar();
Location();
Services(); 
MSearch();
Mlocation();
Story();
Slider();